### ISSUE TITLE
Rucio Integration with the VRE Data Lake

### ISSUE THREAD

**Issue by goseind** [swan-cern/swan-charts#157]
### Motivation

Based on our recent discussions, we would like to suggest integrating Rucio with the Rucio VRE Data Lake within SWAN. This integration should be made available as an option in the Helm Charts, allowing third parties to install it, as well as in the existing CERN instance. Upon login, the user could then select an instance to connect to:

![swan_rucio_setup](https://github.com/swan-cern/swan-charts/assets/87760323/f7ddabb6-c82c-44ec-8b0b-1b2470b7ac45)

Within JupyterLab the user would then be able to use Rucio to access the Data Lake instance:

![rucio_extension_showcase_vre_2](https://github.com/swan-cern/swan-charts/assets/87760323/e3d37cf5-7df2-479a-bcd0-9f9372e2f839)

### Modifications

To achieve this the following enhancements are necessary:

- [ ] Installation of the [Rucio Jupyter Extension](https://github.com/rucio/jupyterlab-extension) in the *singleuser* image
- [ ] Installation of the Rucio CLI in the *singleuser* image
- [ ] Pre-configuration of the *singleuser* environment with the necessary Rucio configuration
- [ ] Token exchange mechanism to place a valid token into a file for the extension and Rucio CLI to use

Below is a preliminary example of the necessary modifications in the JupyterHub configuration:

```yaml
hub:
  config:
    RucioAuthenticator:
      # client_id: "" # set through secret
      # client_secret: "" # set through secret
      authorize_url: https://iam-escape.cloud.cnaf.infn.it/authorize
      token_url: https://iam-escape.cloud.cnaf.infn.it/token
      userdata_url: https://iam-escape.cloud.cnaf.infn.it/userinfo
      username_key: preferred_username
      scope:
        - openid
        - profile
        - email
  extraConfig:
    token-exchange: |
      import pprint
      import os
      import warnings
      import requests
      from oauthenticator.generic import GenericOAuthenticator

      # custom authenticator to exchange the access token for a refresh token for rucio OIDC to work
      class RucioAuthenticator(GenericOAuthenticator):
          def __init__(self, **kwargs):
              super().__init__(**kwargs)
              self.enable_auth_state = True

          def exchange_token(self, token):
              params = {
                  'client_id': self.client_id,
                  'client_secret': self.client_secret,
                  'grant_type': 'urn:ietf:params:oauth:grant-type:token-exchange',
                  'subject_token': token,
                  'scope': 'openid email profile',
                  'audience': 'rucio'
              }
              response = requests.post(self.token_url, data=params)
              refresh_token = response.json()['access_token']
              return refresh_token
          
          async def pre_spawn_start(self, user, spawner):
              auth_state = await user.get_auth_state()
              pprint.pprint(auth_state)
              if not auth_state:
                  # user has no auth state
                  return
              
              # define token environment variable from auth_state
              spawner.environment['REFRESH_TOKEN'] = self.exchange_token(auth_state['access_token'])
      
      # set the above authenticator as the default
      c.JupyterHub.authenticator_class = RucioAuthenticator

      # enable authentication state
      c.GenericOAuthenticator.enable_auth_state = True

      if 'JUPYTERHUB_CRYPT_KEY' not in os.environ:
          warnings.warn(
              "Need JUPYTERHUB_CRYPT_KEY env for persistent auth_state.\n"
              "    export JUPYTERHUB_CRYPT_KEY=$(openssl rand -hex 32)"
          )
          c.CryptKeeper.keys = [os.urandom(32)]

singleuser:
  # The lifecycle hooks are used to create the Rucio configuration file,
  # and the token file by copying the REFRESH_TOKEN from the environment variable to the token file.
  lifecycleHooks:
    postStart:
      exec:
        command:
          - "sh"
          - "-c"
          - >
            echo -n $REFRESH_TOKEN > /home/jovyan/token;
            mkdir -p /opt/rucio/etc;
            echo "[client]" >> /opt/rucio/etc/rucio.cfg;
            echo "rucio_host = https://vre-rucio.cern.ch" >> /opt/rucio/etc/rucio.cfg;
            echo "auth_host = https://vre-rucio-auth.cern.ch" >> /opt/rucio/etc/rucio.cfg;
            echo "ca_cert = /opt/cert.pem" >> /opt/rucio/etc/rucio.cfg;
            echo "account = $JUPYTERHUB_USER" >> /opt/rucio/etc/rucio.cfg;
            echo "auth_type = oidc" >> /opt/rucio/etc/rucio.cfg;
            echo "oidc_audience = rucio" >> /opt/rucio/etc/rucio.cfg;
            echo "auth_token_file_path = /home/jovyan/token" >> /opt/rucio/etc/rucio.cfg;
        
  image:
    name: ghcr.io/goseind/singleuser-base 
    tag: latest
    pullPolicy: Always
  extraFiles:
    ca:
      mountPath: /opt/cert.pem # This can be placed into the above image
      stringData: |
        -----BEGIN CERTIFICATE-----
       <cert>
        -----END CERTIFICATE-----
  cmd: null
  extraEnv:
    RUCIO_MODE: "replica"
    RUCIO_WILDCARD_ENABLED: "1"
    RUCIO_BASE_URL: "https://vre-rucio.cern.ch"
    RUCIO_AUTH_URL: "https://vre-rucio-auth.cern.ch"
    RUCIO_DISPLAY_NAME: "VRE-RUCIO"
    RUCIO_NAME: "vre-rucio.cern.ch"
    RUCIO_SITE_NAME: "ROAMING"
    RUCIO_OIDC_AUTH: "env"
    RUCIO_OIDC_ENV_NAME: "REFRESH_TOKEN"
    RUCIO_DEFAULT_AUTH_TYPE: "oidc"
    RUCIO_OAUTH_ID: "rucio"
    RUCIO_DEFAULT_INSTANCE: "vre-rucio.cern.ch"
    RUCIO_DESTINATION_RSE: "CERN-EOS"
    RUCIO_RSE_MOUNT_PATH: "/eos/escape"
    RUCIO_PATH_BEGINS_AT: "5"
    RUCIO_CA_CERT: "/opt/cert.pem"
```

This [GitHub repository](https://github.com/goseind/jupyterlab-extension-setup) provides a complete example of a local setup with the above code. There are multiple approaches to solving this problem, including incorporating certain configurations directly into the image and utilizing an extension for token exchange.

We'd love to set this up and are looking forward to your feedback on this 🚀 😃
